---

- name: RedHat | Check if oracle jdk already installed
  command: rpm -q jdk1.8.0_60-1.8.0_60-fcs.x86_64
  register: rpm_check

- name: RedHat | Download oracle rpm
  get_url:
      url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm
      validate_certs: no
      headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
      dest: /tmp/oracle.rpm
  when: rpm_check.stdout != 'jdk1.8.0_60-1.8.0_60-fcs.x86_64'

- name: Installe oracle rpm
  yum:
      name: /tmp/oracle.rpm
      state: present
