--- 
# defaults file for bind
bind_version: "bind"
bind_address: [ '127.0.0.1', '192.168.0.0/16', '172.16.0.0/12', '10.0.0.0/8' ]
bind_deploy_zone_example: false
bind_deploy_zone_name: "labs.lan"
bind_ddns_enable: false
bind_ddns_scripts: "{{ bind_ddns_enable }}"
