tomcat_version: 8.0.23
tomcat_archive_file: "apache-tomcat-{{tomcat_version}}.tar.gz"
tomcat_download_url: "http://archive.apache.org/dist/tomcat/tomcat-{{tomcat_version[0]}}/v{{tomcat_version}}/bin/{{tomcat_archive_file}}"
tomcat_libraries_download_url: "http://archive.apache.org/dist/tomcat/tomcat-{{tomcat_version[0]}}/v{{tomcat_version}}/bin/extras/"
tomcat_libraries:
  - { name: catalina-jmx-remote.jar  , dir: lib }
  - { name: tomcat-juli-adapters.jar , dir: lib }

# Install directory
tomcat_install_dir: "/srv"
tomcat_root_dir: "{{tomcat_install_dir}}/tomcat"

# Port definition
tomcat_http_port: 8080
tomcat_ajp_port: 8009
tomcat_jmx_registry_port: 10080
tomcat_jmx_server_port: 10081

ipv6_disable: True

# User definition
tomcat_user: "tomcat"
tomcat_group: "tomcat"
tomcat_admin_user: "admin"
tomcat_admin_pass: "admin"

# Tuning configuration
tomcat_heap_size_prct: 0.85
tomcat_min_heap_size: "{{(ansible_memtotal_mb*tomcat_heap_size_prct)|int }}M"
tomcat_max_heap_size: "{{tomcat_min_heap_size}}"
tomcat_min_metaspace_size: 128M
tomcat_max_metaspace_size: 128M

# Directory and log files
tomcat_gc_log_file: "{{tomcat_root_dir}}/logs/gc.log"
tomcat_heap_dump_dir: "{tomcat_root_dir}}/logs/"
