---
- name: Generate configuration
  command: "{{ centreon_script_dir }}/centreon-host-add {{ centreon_tmp_dir }}/hosts.csv"
  notify: Deploy configuration
  delegate_to: "{{ centreon_server }}"

- name: Deploy configuration
  command: "{{ centreon_script_dir }}/centreon-poller-reload"
  notify: Purge temporary directory
  delegate_to: "{{ centreon_server }}"

- name: Purge temporary directory
  file:
    path: "{{ centreon_script_dir }}/hosts/*"
    state: absent
  delegate_to: "{{ centreon_server }}"
