---
- name: firewall | Setting firewall rules
  firewalld:
    port:      "{{item}}/tcp"
    permanent: true
    state:     enabled
    immediate: yes
  with_items:
    - 9200
    - 9300
  when: firewall_type == 'firewalld'
