---
- name: admin_script | Deploy admin script
  copy:
    src:   "{{ item.src }}"
    dest:  "{{ item.dest }}"
    owner: root
    group: root
    mode:  0755
  with_items:
    - src:  usr/local/bin/galera-ctl
      dest: /usr/local/bin/galera-ctl
    - src:  usr/local/bin/galera-status
      dest: /usr/local/bin/galera-status
