---

- name: configure_wsrep_user | creating wsrep user
  mysql_user:
    name: "{{ wsrep_sst_user }}"
    host: "{{ item }}"
    password: "{{ wsrep_sst_password }}"
    priv: "*.*:ALL,GRANT"
  with_items:
    - '%'
    - '127.0.0.1'
    - '::1'
    - localhost
