---

# Configure firewall
- name: configure_firewall | allowed galera port
  firewalld:
    port:      "{{item}}"
    permanent: true
    state:     enabled
    immediate: yes
  with_items:
    - "3306/tcp"
    - "4567/tcp"
    - "4568/tcp"
    - "4444/tcp"
    - "4567/udp"
