---
- name: redhat | adding mariadb repo
  template:
    src: "etc/yum.repos.d/MariaDB.repo.j2"
    dest: "/etc/yum.repos.d/MariaDB.repo"
    owner: "root"
    group: "root"
  register: repo_added

- name: redhat | installing mariadb mysql
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'MySQL-python'
    - 'socat'
    - 'MariaDB-server'
    - 'galera'
    - 'percona-xtrabackup'

- name: redhat | ensuring mariadb mysql is enabled on boot and started
  service:
    name: "mysql"
    state: "started"
    enabled: yes
