basic_packages:
  - ca-certificates
  - bash-completion
  - diffutils
  - file
  - iproute
  - less
  - lsof
  - moreutils
  - psmisc
  - rsync
  - screen
  - strace
  - sudo
  - tcpdump
  - unzip
  - vim
  - dstat

host_packages:
  - ntp
  - acpid
  - tcpdump
  - iotop
  - dstat

remove_packages:
  - locate
  - mlocate
  - nano
