---
basic_packages:
  - ca-certificates
  - bash-completion
  - diffutils
  - file
  - iproute
  - less
  - lsof
  - moreutils
  - patch
  - psmisc
  - rsync
  - screen
  - ssh
  - ssl-cert
  - strace
  - sudo
  - tcpdump
  - unzip
  - vim

host_packages:
  - ntp
  - acpid
  - tcpdump
  - iotop
  - dstat

remove_packages:
  - locate
  - mlocate
  - nano
  - openbsd-inetd
