---
# Global flag
enable_galera_monitoring: true  #defines if cluster node monitoring should be enabled for mariadb
enable_nagios_monitoring: "{{ enable_galera_monitoring }}"  #defines if nagios monitoring should be enabled for mariadb

# Galera variables
galera_allow_root_from_any: false     #defines if root logins should be allowed from any host
galera_cluster_name: 'galera-cluster' # Define the name of the cluster...define here or in group_vars/group
galera_cluster_bind_address: 0.0.0.0  #define bind address for galera cluster...
galera_cluster_nodes_group: 'galera-cluster-nodes' # defines groups nodes
mariadb_master_node: "{{ groups[galera_cluster_nodes_group][0] }}"

# Cluster monitor script
galera_monitor_script_name: 'galera-check'
galera_monitor_script_path: '/usr/local/bin'
 
# Mariadb Version
mariadb_version: 10.1

# MariaDB debian Repository
mariadb_debian_repo: 'deb http://ftp.osuosl.org/pub/mariadb/repo/{{ mariadb_version }}/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} main'
mariadb_debian_repo_key: '0xcbcb082a1bb943db'
mariadb_debian_repo_keyserver: 'keyserver.ubuntu.com'

# MariaDB RedHat repository
mariadb_redhat_repo: 'http://yum.mariadb.org/{{ mariadb_version }}/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version|int}}-amd64'
mariadb_redhat_repo_key: 'https://yum.mariadb.org/RPM-GPG-KEY-MariaDB'

# MariaDB Tuning
mariadb_innodb_buffer_pool_size_prct: 0.8
mariadb_innodb_buffer_pool_size: "{{ (ansible_memtotal_mb*mariadb_innodb_buffer_pool_size_prct)|int }}M"

mariadb_root_password: 'changeme' #defines mariadb root password...generate using echo password | mkpasswd -s -m sha-512

# Mail alerting
notify_mail_from: 'galeranotify@{{ smtp_domain_name }}'  #defines email address that cluster notifications will be sent from
notify_mail_to: '{{ email_notifications }}'
notify_smtp_server: '{{ smtp_server }}'  #defines smtp server to send notifications through
pri_domain_name: 'example.org'
reconfigure_galera: false  #defines if the cluster should be reconfigured
smtp_domain_name: '{{ pri_domain_name }}' #defines smtp domain for email...define here or globally in group_vars/all/email
smtp_server: 'smtp.{{ pri_domain_name }}'  #defines smtp server to send email through...define here or globally in group_vars/all/servers
email_notifications: 'notifications@{{ smtp_domain_name }}'  #defines email address to receive notifications...define here or in group_vars/group

wsrep_sst_user: wsrepuser # defines xtrabackup user
wsrep_sst_password: dO9qygn8 # defines xtrabackup password

# defaults file for ansible-mariadb-galera-cluster
monitoring_server_fqdn: '%' # defines the remote monitoring serveur
monitoring_db_password: 'monitoringuser'  #defines the password for monitoring db monitoring...define here or globally in group_vars/all/accounts
monitoring_db_user: 'monitoringuser'  #defines the user for monitoring db monitoring...define here or globally in group_vars/all/accounts

deb_db_password: '{{ mariadb_root_password }}'  #defines debian db password...generate using echo password | mkpasswd -s -m sha-512
